language: c
matrix:
  include:
    - language: elixir
      elixir:
        - '1.5'
      env:
        - SECRET_KEY=ultrasupersecretkey
      script:
        - cd elixir-elm/backend
        - mix deps.get
        - mix compile
        - mix test
