language: c
dist: trusty
matrix:
  include:
    - language: elixir
      otp_release: 22.2
      elixir: 1.10.1
      env:
        - SECRET_KEY=ultrasupersecretkey

      before_install:
        - cd elixir-elm/backend

      script:
        - mix deps.get
        - MIX_ENV=test mix deps.compile
        - mix test
