language: c
matrix:
  include:
    - language: elixir
      elixir:
        - '1.10.1'
      env:
        - SECRET_KEY=ultrasupersecretkey

      before_install:
        - cd elixir-elm/backend

      script:
        - mix compile
        - mix test
