language: c
dist: trusty
services:
  - postgresql
matrix:
  include:
    - language: elixir
      otp_release: 22.2
      elixir: 1.10.1
      env:
        - SECRET_KEY=ultrasupersecretkey

      before_install:
        - cd elixir-elm/backend

      script:
        - psql -c "CREATE DATABASE phoenix_test;" -U postgres
        - psql -c "CREATE USER phoenix_test with password 'phoenix_test';" -U postgres
        - psql -c "CREATE USER phoenix_test with SUPERUSER;" -U postgres
        - mix deps.get
        - MIX_ENV=test mix deps.compile
        - mix test
